name: Build test document

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Typst common steps
        uses: ./.github/actions/typst-steps
        with:
          input_file: tests/test-make-doc.typ
