name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  TYPST_INPUT: tests/test-compile-doc.typ
  OUTPUT_PDF: ${{ github.event.repository.name }}-${{ github.ref_name }}.pdf

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CJK Typst compile steps
        uses: ./.github/actions/typst-steps
        with:
          input_file: ${{ env.TYPST_INPUT }}
          output_file: ${{ env.OUTPUT_PDF }}

      - name: Create GitHub Release (draft)
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.OUTPUT_PDF }}
          draft: true
          generate_release_notes: true
